  version: '3.9'
  services:
    db:
      image: postgres:14-alpine
      ports:
        - 5453:5432
      volumes:
        - ~/gateway-router/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=root
        # - POSTGRES_DB=gateway_router